### ISSUE TITLE
How to invite?

### ISSUE THREAD

**Issue by Dominic8978** [o5k/yukari#9]
When I press the invite on my server literally says invite for friends I really need help on to invite the bot so can you please help me since I’m really struggling with this.

**Comment by o5k** [comment]
I don't currently operate a public instance of Yukari. But, you can run it yourself w/ the instructions given. If more are interested I can put up an instance again

**Comment by BackedUpBooty** [comment]
Just came across this, if you're able to put up an instance again that would be amazing, trying to adapt your instructions to a Synology NAS is a bit beyond my skillset unfortunately. After our shake in Kyoto today this would be such a helpful tool to have access to.
